### ISSUE TITLE
Large file copy fails on v0.5

### ISSUE THREAD

**Issue by Wrangler491** [mbtaylor1982/ReSDMAC#10] opened 2024-10-08 20:17 UTC
Set up: Amiga 3000T with BFG9060 running at 50MHz, 128MB of local RAM, no motherboard FastRam, 2MB chip,
Buddha IDE card in a Zorro slot for booting pre v0.4
OS3.2.2.1 clean install on SCSI unit 5, second SCSI HD on unit 2.  

Copying a 34MB file from one device to the other worked 3 times out of 3 on v0.4 and failed 3 times out of 3 on v0.5.

Changing the transfer mask on both devices to ‘0x7fffffc’ didn’t help

**Comment by mbtaylor1982** [comment] 2024-10-08 22:16
I've tried to recreate this issue on my ReAmiga 3000 with 16MB Fast RAM 2MB Chip RAM standard 030 @ 25Mhz and no zorro cards.

I created a 34MB file and successfully transferred it several times.

I suspect this could be a timing issue with the BFG. if other people with a BFG can also test this it would be appreciated until i have chance to finish building mine.

**Comment by Wrangler491** [comment] 2024-10-09 19:05
I can reproduce this bug using only the on-board '030 and chipmem -> fine in v0.4, results in system hanging in v0.5

**Comment by mbtaylor1982** [comment] 2024-10-14 22:34
@Wrangler491 can you test with https://github.com/mbtaylor1982/ReSDMAC/releases/tag/v0.6 to see if this resolves your issue? it may not as I could not reproduce it with my setup.

**Comment by Wrangler491** [comment] 2024-10-15 19:43
Issue resolved in v0.6.  Large file transfer also works with sync turned on.

**Closed** 2024-10-15 19:47 UTC
Labels: bug
